[build]
  publish = "public"
  command = "hugo --gc --minify --config production.toml"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.52"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.52"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
